### ISSUE TITLE
不能取消

### ISSUE THREAD

**Issue by itachaaa** [leolee9086/headingIndex#1]
1. 不能取消使用这个标题
2. 实际只有2个实例设置

**Comment by leolee9086** [comment]
0.0.3版应该有四个设置实例，在插件的安装文件夹里面， readme里面没有说清楚，要启用它们需要自己操作上传或者移动这些实例，在插件图标上右键之后应该会打开上传窗口。

取消标题也就是使用空的标题编号传入这个设置(也就是所有标题级别全部留空)：

```javascript
["","","","","",""]
```

之后有时间做一个编辑界面算了

感谢反馈

**Comment by leolee9086** [comment]
https://github.com/leolee9086/headingIndex/issues/2

**Comment by leolee9086** [comment]
> 1. 不能取消使用这个标题
> 2. 实际只有2个实例设置

0.0.4版应该已经可以在界面上编辑标题编号样式了,实例设置还是不自动拷贝太多了,需要的话可以去插件安装文件夹找,每个版本这些实例文件都可能不一样,自动拷贝可能让人疑惑.
