### ISSUE TITLE
罗马数字10不正确

### ISSUE THREAD

**Issue by TyroneXie** [leolee9086/headingIndex#11]
![image](https://github.com/leolee9086/headingIndex/assets/26218850/d41ed500-47cc-4a9a-a1fb-dd31b0b724f8)
如图，罗马数字10应该是X，但现实为I了

**Comment by leolee9086** [comment]
收到  最近有些忙  等国庆回来把ai插件处理完修复这些已知的问题

**Comment by leolee9086** [comment]
https://github.com/leolee9086/headingIndex/releases/tag/0.0.9
新版修复了罗马数字的问题,抱歉一直没有处理,issue我先关闭了
