### ISSUE TITLE
安装插件后无法打开配置文件菜单

### ISSUE THREAD

**Issue by ToSTA0708** [leolee9086/headingIndex#3]
安装插件后左键点击无法打开配置文件菜单，右键点击上传配置文件之后，没有效果

**Comment by ToSTA0708** [comment]
上传配置文件后，无法创建菜单
![image](https://github.com/leolee9086/headingIndex/assets/43084789/d31d8122-7201-4bbf-9987-425a82998c50)

**Comment by leolee9086** [comment]
后面的版本这里会加上校验，点击上传配置文件是说的右键点击那个吗？那里仅支持安全上下文 ，也就是127.0.0.1、localhost 之类开头的地址访问思源或者https协议下才能使用，暂时你可以试试重装插件看能不能恢复使用

**Comment by leolee9086** [comment]
另外你是上传了一个什么样的配置文件？  我看是不是文件名会造成问题

**Comment by ToSTA0708** [comment]
规避方法：在文件夹中添加一个名为“当前全局配置.json”配置文件，并上传，规避该问题。

以下是我的排查思路，希望能对作者有所帮助：
根据报错提示，找到了index.js代码中的288行，报错原因为 `this.设置字典.当前全局配置` 这个值为undefine：
![image](https://github.com/leolee9086/headingIndex/assets/43084789/fb133871-8fc5-4ace-9830-28f33c42e879)
进一步寻找`this.设置字典.当前全局配置`这个值赋值位置，应该是在“覆盖默认设置”方法中：
![image](https://github.com/leolee9086/headingIndex/assets/43084789/42b83de5-ed13-43d4-b29c-8c7431529f74)
插件刚安装的情况下，data\storage\petal\headingIndex文件夹下不存在名为"lastValues.json"的配置文件，因此`this.设置字典.当前全局配置`的值为空，导致在288行发生错误。

**Comment by leolee9086** [comment]
啊 菜鸡落泪  我想起来了  写了if之后去上了个厕所就没写else了。。。。。。。。。 感谢感谢  0.0.7应该已经修了  另外你可以在判定lastValues是否存在的那个if后面加个else{this.设置字典.当前全局配置={}} 也能临时修正一下

**Comment by leolee9086** [comment]
上传了0.0.7应该已经修复了初次安装的问题  水平有点菜  见谅见谅  issue 我先关闭了 有问题可以再提蛤
