### ISSUE TITLE
编号存在问题

### ISSUE THREAD

**Issue by ToSTA0708** [leolee9086/headingIndex#5]
中文超过9后应该是十、十一、十二等
![image](https://github.com/leolee9086/headingIndex/assets/43084789/b4f7962a-1f64-464b-b1a5-660a59e367a7)

**Comment by leolee9086** [comment]
额  这个    我要不支持一下自定义转换函数？

**Comment by leolee9086** [comment]
https://github.com/leolee9086/headingIndex/issues/6

**Comment by leolee9086** [comment]
> 中文超过9后应该是十、十一、十二等 ![image](https://user-images.githubusercontent.com/43084789/251162692-b4f7962a-1f64-464b-b1a5-660a59e367a7.png)

新版支持在代码片段中添加转换函数，你的需求通过添加代码片段解决，例如使用以下实例：

```javascript
document.currentScript.indexFormatters=[
{
name:'chs',
formatter:(num,indexObj,blockId)=>{
let list={
10:"十",
11:"十一",
12:"十二",
13:"十三",
14:"十四",
15:"十五",
16:"十六",
17:"十七",
18:"十八",
19:"十九",
}
console.log(list[num],indexObj.ch
)
return list[num]||indexObj.ch
}
}
]
```
把它写到代码片段里，然后就可以通过`h1.chs`来使用它
issue 我先关闭了
